openapi: 3.0.3
info:
  title: @project.description@
  version: @project.version@
tags:
  - name: Persons
paths:
  /persons:
    post:
      tags:
        - Persons
      operationId: create-one-person
      summary: Create one person.
      requestBody:
        $ref: '#/components/schemas/CreateOnePersonRequest'
      responses:
        '201':
          description: Person created.
          headers:
    get:
      tags:
        - Persons
      operationId: retrieve-all-persons
      summary: Retrieve all persons.
      responses:
        content:
          application/json:
            $ref: "#/components/schemas/RetrieveAllPersonsResponse"
components:
  schemas:
    CreateOnePersonRequest:
        type: object
        properties:
          a1:
            type: string
            description: Names.
          a2:
            type: string
            description: First surname.
          a3:
            type: string
            description: Second surname.
          a4:
            type: string
            description: Gender.
          a5:
            type: string
            description: Birthday
    RetrieveAllPersonsResponse:
      type: object
      properties:
        a0:
          type: string
          description: Unique identifier.
        a1:
          type: string
          description: Names.
        a2:
          type: string
          description: First surname.
        a3:
          type: string
          description: Second surname.
        a4:
          type: string
          description: Gender.
        a5:
          type: string
          description: Birthday
        a6:
          type: string
          description: CURP.
